// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MCMC_cpp_internal
List MCMC_cpp_internal(List data_objects, List indolents, List taus, List H, List P, List psi, List beta, List strategies, double t0, int M, int thin, int burnin, int verbose, int save_latent, int debug, int use_bug, bool use_orig_prop, bool I_marginalize_CEN, bool I_marginalize_PRE, bool I_marginalize_CLI, std::string latent_dir, int latent_dump, std::string file_prefix, IntegerVector latent_order);
RcppExport SEXP _baclava_MCMC_cpp_internal(SEXP data_objectsSEXP, SEXP indolentsSEXP, SEXP tausSEXP, SEXP HSEXP, SEXP PSEXP, SEXP psiSEXP, SEXP betaSEXP, SEXP strategiesSEXP, SEXP t0SEXP, SEXP MSEXP, SEXP thinSEXP, SEXP burninSEXP, SEXP verboseSEXP, SEXP save_latentSEXP, SEXP debugSEXP, SEXP use_bugSEXP, SEXP use_orig_propSEXP, SEXP I_marginalize_CENSEXP, SEXP I_marginalize_PRESEXP, SEXP I_marginalize_CLISEXP, SEXP latent_dirSEXP, SEXP latent_dumpSEXP, SEXP file_prefixSEXP, SEXP latent_orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data_objects(data_objectsSEXP);
    Rcpp::traits::input_parameter< List >::type indolents(indolentsSEXP);
    Rcpp::traits::input_parameter< List >::type taus(tausSEXP);
    Rcpp::traits::input_parameter< List >::type H(HSEXP);
    Rcpp::traits::input_parameter< List >::type P(PSEXP);
    Rcpp::traits::input_parameter< List >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< List >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type strategies(strategiesSEXP);
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type save_latent(save_latentSEXP);
    Rcpp::traits::input_parameter< int >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< int >::type use_bug(use_bugSEXP);
    Rcpp::traits::input_parameter< bool >::type use_orig_prop(use_orig_propSEXP);
    Rcpp::traits::input_parameter< bool >::type I_marginalize_CEN(I_marginalize_CENSEXP);
    Rcpp::traits::input_parameter< bool >::type I_marginalize_PRE(I_marginalize_PRESEXP);
    Rcpp::traits::input_parameter< bool >::type I_marginalize_CLI(I_marginalize_CLISEXP);
    Rcpp::traits::input_parameter< std::string >::type latent_dir(latent_dirSEXP);
    Rcpp::traits::input_parameter< int >::type latent_dump(latent_dumpSEXP);
    Rcpp::traits::input_parameter< std::string >::type file_prefix(file_prefixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type latent_order(latent_orderSEXP);
    rcpp_result_gen = Rcpp::wrap(MCMC_cpp_internal(data_objects, indolents, taus, H, P, psi, beta, strategies, t0, M, thin, burnin, verbose, save_latent, debug, use_bug, use_orig_prop, I_marginalize_CEN, I_marginalize_PRE, I_marginalize_CLI, latent_dir, latent_dump, file_prefix, latent_order));
    return rcpp_result_gen;
END_RCPP
}
// predict_ODX
List predict_ODX(List H, List P, List psi, List beta, double t0, Rcpp::NumericVector screening_schedule_r, Rcpp::NumericVector lambda_ages_r, Rcpp::NumericVector lambda_rates_r, Rcpp::NumericMatrix posteriors, Rcpp::CharacterVector posterior_column_names);
RcppExport SEXP _baclava_predict_ODX(SEXP HSEXP, SEXP PSEXP, SEXP psiSEXP, SEXP betaSEXP, SEXP t0SEXP, SEXP screening_schedule_rSEXP, SEXP lambda_ages_rSEXP, SEXP lambda_rates_rSEXP, SEXP posteriorsSEXP, SEXP posterior_column_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type H(HSEXP);
    Rcpp::traits::input_parameter< List >::type P(PSEXP);
    Rcpp::traits::input_parameter< List >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< List >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type screening_schedule_r(screening_schedule_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_ages_r(lambda_ages_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda_rates_r(lambda_rates_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type posteriors(posteriorsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type posterior_column_names(posterior_column_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_ODX(H, P, psi, beta, t0, screening_schedule_r, lambda_ages_r, lambda_rates_r, posteriors, posterior_column_names));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_baclava_MCMC_cpp_internal", (DL_FUNC) &_baclava_MCMC_cpp_internal, 24},
    {"_baclava_predict_ODX", (DL_FUNC) &_baclava_predict_ODX, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_baclava(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
