# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMC_cpp_internal <- function(data_objects, indolents, taus, H, P, psi, beta, strategies, t0, M, thin, burnin, verbose, save_latent, debug, use_bug, use_orig_prop, I_marginalize_CEN, I_marginalize_PRE, I_marginalize_CLI, latent_dir, latent_dump, file_prefix, latent_order) {
    .Call('_baclava_MCMC_cpp_internal', PACKAGE = 'baclava', data_objects, indolents, taus, H, P, psi, beta, strategies, t0, M, thin, burnin, verbose, save_latent, debug, use_bug, use_orig_prop, I_marginalize_CEN, I_marginalize_PRE, I_marginalize_CLI, latent_dir, latent_dump, file_prefix, latent_order)
}

predict_ODX <- function(H, P, psi, beta, t0, screening_schedule_r, lambda_ages_r, lambda_rates_r, posteriors, posterior_column_names) {
    .Call('_baclava_predict_ODX', PACKAGE = 'baclava', H, P, psi, beta, t0, screening_schedule_r, lambda_ages_r, lambda_rates_r, posteriors, posterior_column_names)
}

